export * from './../components/ui/ScrollSnap/Andromeda/types.ts'
export * from './../components/portfolios/WorkSection/Andromeda/types.ts'
export * from './../components/portfolios/IntroductionSection/Andromeda/types.ts'
export * from './../components/portfolios/HeroSection/Andromeda/types.ts'
export * from './../components/portfolios/ContactForm/Andromeda/types.ts'
export * from './props-components.ts'
